catalog_url: "https://w3id.org/ejp-rd/fairdatapoints/wp13/catalog/bf209b8a-eb67-4f35-864f-6d02228e1d91"
dataset_file: "Huntington-resource/datasets.csv"
distribution: "Huntington-resource/distributions.csv"
