name: Populate WP13 FDP

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup python 3.8
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # Extact catalog url
      - name: print body
        env:
          BODY: ${{ github.event.comment.body }}
        run: echo "$BODY"
